package com.linxi.entity;

import java.io.Serializable;
import java.sql.Timestamp;

public class Appointment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.a_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.a_cl_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer aClId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.a_time
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Timestamp aTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.a_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer aHId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.a_type_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer aTypeId;

    private Integer aStatus;

    private Timestamp aCreateTime;

    /**
     * 客户名称
     */
    private String cName;

    /**
     * 预约门诊
     */
    private String hName;

    /**
     * 预约类型
     */
    private String aType;

    /**
     * 预约项目
     */
    private String clProject;

    /**
     * 负责人名称
     */
    private String uName;

    /**
     * 预交金额
     */
    private Integer clEarnest;

    /**
     * 成交总金额
     */
    private Integer sSum;

    /**
     * 客户编号
     */
    private Integer cId;

    /**
     * 线索编号
     */
    private Integer clId;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.a_id
     *
     * @return the value of appointment.a_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.a_id
     *
     * @param aId the value for appointment.a_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.a_cl_id
     *
     * @return the value of appointment.a_cl_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getaClId() {
        return aClId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.a_cl_id
     *
     * @param aClId the value for appointment.a_cl_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setaClId(Integer aClId) {
        this.aClId = aClId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.a_time
     *
     * @return the value of appointment.a_time
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Timestamp getaTime() {
        return aTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.a_time
     *
     * @param aTime the value for appointment.a_time
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setaTime(Timestamp aTime) {
        this.aTime = aTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.a_h_id
     *
     * @return the value of appointment.a_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getaHId() {
        return aHId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.a_h_id
     *
     * @param aHId the value for appointment.a_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setaHId(Integer aHId) {
        this.aHId = aHId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.a_type_id
     *
     * @return the value of appointment.a_type_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getaTypeId() {
        return aTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.a_type_id
     *
     * @param aTypeId the value for appointment.a_type_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setaTypeId(Integer aTypeId) {
        this.aTypeId = aTypeId;
    }

    public Integer getaStatus() {
        return aStatus;
    }

    public void setaStatus(Integer aStatus) {
        this.aStatus = aStatus;
    }

    public Timestamp getaCreateTime() {
        return aCreateTime;
    }

    public void setaCreateTime(Timestamp aCreateTime) {
        this.aCreateTime = aCreateTime;
    }

    public String getcName() {
        return cName;
    }

    public void setcName(String cName) {
        this.cName = cName;
    }

    public String gethName() {
        return hName;
    }

    public void sethName(String hName) {
        this.hName = hName;
    }

    public String getaType() {
        return aType;
    }

    public void setaType(String aType) {
        this.aType = aType;
    }

    public String getuName() {
        return uName;
    }

    public void setuName(String uName) {
        this.uName = uName;
    }

    public String getClProject() {
        return clProject;
    }

    public void setClProject(String clProject) {
        this.clProject = clProject;
    }

    public Integer getClEarnest() {
        return clEarnest;
    }

    public void setClEarnest(Integer clEarnest) {
        this.clEarnest = clEarnest;
    }

    public Integer getsSum() {
        return sSum;
    }

    public void setsSum(Integer sSum) {
        this.sSum = sSum;
    }

    public Integer getcId() {
        return cId;
    }

    public void setcId(Integer cId) {
        this.cId = cId;
    }

    public Integer getClId() {
        return clId;
    }

    public void setClId(Integer clId) {
        this.clId = clId;
    }

    public Appointment() {
    }

    public Appointment(Integer aId, Integer aClId, Timestamp aTime, Integer aHId, Integer aTypeId, Integer aStatus, Timestamp aCreateTime) {
        this.aId = aId;
        this.aClId = aClId;
        this.aTime = aTime;
        this.aHId = aHId;
        this.aTypeId = aTypeId;
        this.aStatus = aStatus;
        this.aCreateTime = aCreateTime;
    }
}