package com.linxi.entity;

import java.io.Serializable;
import java.sql.Timestamp;

public class Arrive implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrive.ar_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer arId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrive.ar_a_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer arAId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrive.ar_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer arHId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrive.ar_cause
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private String arCause;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrive.ar_invalid
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer arInvalid;

    /**
     * 客户编号
     */
    private Integer cId;

    /**
     * 客户姓名
     */
    private String cName;

    /**
     * 门诊编号
     */
    private Integer hId;

    /**
     * 门诊名称
     */
    private String hName;

    /**
     * 线索编号
     */
    private Integer clId;

    /**
     * 负责人编号
     */
    private Integer clUId;

    /**
     * 预约编号
     */
    private Integer aId;

    /**
     * 预约时间
     */
    private Timestamp aTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table arrive
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrive.ar_id
     *
     * @return the value of arrive.ar_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getArId() {
        return arId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrive.ar_id
     *
     * @param arId the value for arrive.ar_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setArId(Integer arId) {
        this.arId = arId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrive.ar_a_id
     *
     * @return the value of arrive.ar_a_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getArAId() {
        return arAId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrive.ar_a_id
     *
     * @param arAId the value for arrive.ar_a_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setArAId(Integer arAId) {
        this.arAId = arAId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrive.ar_h_id
     *
     * @return the value of arrive.ar_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getArHId() {
        return arHId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrive.ar_h_id
     *
     * @param arHId the value for arrive.ar_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setArHId(Integer arHId) {
        this.arHId = arHId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrive.ar_cause
     *
     * @return the value of arrive.ar_cause
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public String getArCause() {
        return arCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrive.ar_cause
     *
     * @param arCause the value for arrive.ar_cause
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setArCause(String arCause) {
        this.arCause = arCause;
    }

    public Integer getArInvalid() {
        return arInvalid;
    }

    public void setArInvalid(Integer arInvalid) {
        this.arInvalid = arInvalid;
    }

    public Integer getcId() {
        return cId;
    }

    public void setcId(Integer cId) {
        this.cId = cId;
    }

    public String getcName() {
        return cName;
    }

    public void setcName(String cName) {
        this.cName = cName;
    }

    public Integer gethId() {
        return hId;
    }

    public void sethId(Integer hId) {
        this.hId = hId;
    }

    public String gethName() {
        return hName;
    }

    public void sethName(String hName) {
        this.hName = hName;
    }

    public Integer getClId() {
        return clId;
    }

    public void setClId(Integer clId) {
        this.clId = clId;
    }

    public Integer getClUId() {
        return clUId;
    }

    public void setClUId(Integer clUId) {
        this.clUId = clUId;
    }

    public Integer getaId() {
        return aId;
    }

    public void setaId(Integer aId) {
        this.aId = aId;
    }

    public Timestamp getaTime() {
        return aTime;
    }

    public void setaTime(Timestamp aTime) {
        this.aTime = aTime;
    }

    public Arrive(Integer arId, Integer arAId, Integer arHId, String arCause, Integer arInvalid) {
        this.arId = arId;
        this.arAId = arAId;
        this.arHId = arHId;
        this.arCause = arCause;
        this.arInvalid = arInvalid;
    }

    public Arrive() {

    }
}