package com.linxi.entity;

import java.io.Serializable;

public class Arrive implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrive.ar_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer arId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrive.ar_c_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer arCId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrive.ar_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer arHId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrive.ar_cause
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private String arCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table arrive
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrive.ar_id
     *
     * @return the value of arrive.ar_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getArId() {
        return arId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrive.ar_id
     *
     * @param arId the value for arrive.ar_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setArId(Integer arId) {
        this.arId = arId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrive.ar_c_id
     *
     * @return the value of arrive.ar_c_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getArCId() {
        return arCId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrive.ar_c_id
     *
     * @param arCId the value for arrive.ar_c_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setArCId(Integer arCId) {
        this.arCId = arCId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrive.ar_h_id
     *
     * @return the value of arrive.ar_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getArHId() {
        return arHId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrive.ar_h_id
     *
     * @param arHId the value for arrive.ar_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setArHId(Integer arHId) {
        this.arHId = arHId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrive.ar_cause
     *
     * @return the value of arrive.ar_cause
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public String getArCause() {
        return arCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrive.ar_cause
     *
     * @param arCause the value for arrive.ar_cause
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setArCause(String arCause) {
        this.arCause = arCause;
    }
}