package com.linxi.entity;

import java.io.Serializable;

public class Ctype implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctype.ct_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer ctId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctype.ct_type
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private String ctType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ctype
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctype.ct_id
     *
     * @return the value of ctype.ct_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getCtId() {
        return ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctype.ct_id
     *
     * @param ctId the value for ctype.ct_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setCtId(Integer ctId) {
        this.ctId = ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctype.ct_type
     *
     * @return the value of ctype.ct_type
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public String getCtType() {
        return ctType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctype.ct_type
     *
     * @param ctType the value for ctype.ct_type
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setCtType(String ctType) {
        this.ctType = ctType;
    }

    public Ctype() {
    }

    public Ctype(Integer ctId, String ctType) {
        this.ctId = ctId;
        this.ctType = ctType;
    }
}