package com.linxi.entity;

import java.io.Serializable;

public class Fail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fail.fl_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer flId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fail.fl_c_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer flCId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fail.fl_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer flHId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fail.fl_cause
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private String flCause;

    /**
     * 客户名称
     */
    private String cName;

    /**
     * 未成交门诊名称
     */
    private String hName;

    /**
     * 客户编号
     */
    private Integer cId;

    /**
     * 未成交门诊编号
     */
    private Integer hId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fail
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fail.fl_id
     *
     * @return the value of fail.fl_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getFlId() {
        return flId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fail.fl_id
     *
     * @param flId the value for fail.fl_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setFlId(Integer flId) {
        this.flId = flId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fail.fl_c_id
     *
     * @return the value of fail.fl_c_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getFlCId() {
        return flCId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fail.fl_c_id
     *
     * @param flCId the value for fail.fl_c_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setFlCId(Integer flCId) {
        this.flCId = flCId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fail.fl_h_id
     *
     * @return the value of fail.fl_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getFlHId() {
        return flHId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fail.fl_h_id
     *
     * @param flHId the value for fail.fl_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setFlHId(Integer flHId) {
        this.flHId = flHId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fail.fl_cause
     *
     * @return the value of fail.fl_cause
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public String getFlCause() {
        return flCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fail.fl_cause
     *
     * @param flCause the value for fail.fl_cause
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setFlCause(String flCause) {
        this.flCause = flCause;
    }

    public String getcName() {
        return cName;
    }

    public void setcName(String cName) {
        this.cName = cName;
    }

    public String gethName() {
        return hName;
    }

    public void sethName(String hName) {
        this.hName = hName;
    }

    public Integer getcId() {
        return cId;
    }

    public void setcId(Integer cId) {
        this.cId = cId;
    }

    public Integer gethId() {
        return hId;
    }

    public void sethId(Integer hId) {
        this.hId = hId;
    }

    public Fail(Integer flId, Integer flCId, Integer flHId, String flCause) {
        this.flId = flId;
        this.flCId = flCId;
        this.flHId = flHId;
        this.flCause = flCause;
    }

    public Fail() {

    }
}