package com.linxi.entity;

import java.io.Serializable;

public class Ftype implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ftype.ft_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer ftId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ftype.ft_type
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private String ftType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ftype
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ftype.ft_id
     *
     * @return the value of ftype.ft_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getFtId() {
        return ftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ftype.ft_id
     *
     * @param ftId the value for ftype.ft_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setFtId(Integer ftId) {
        this.ftId = ftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ftype.ft_type
     *
     * @return the value of ftype.ft_type
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public String getFtType() {
        return ftType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ftype.ft_type
     *
     * @param ftType the value for ftype.ft_type
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setFtType(String ftType) {
        this.ftType = ftType;
    }

    public Ftype() {
    }

    public Ftype(Integer ftId, String ftType) {
        this.ftId = ftId;
        this.ftType = ftType;
    }
}