package com.linxi.entity;

import java.io.Serializable;

public class Hospital implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer hId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.h_name
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private String hName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hospital
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.h_id
     *
     * @return the value of hospital.h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.h_id
     *
     * @param hId the value for hospital.h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void sethId(Integer hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.h_name
     *
     * @return the value of hospital.h_name
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public String gethName() {
        return hName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.h_name
     *
     * @param hName the value for hospital.h_name
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void sethName(String hName) {
        this.hName = hName;
    }
}