package com.linxi.entity;

import java.io.Serializable;

public class Paytype implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paytype.pay_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paytype.pay_type
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table paytype
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paytype.pay_id
     *
     * @return the value of paytype.pay_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paytype.pay_id
     *
     * @param payId the value for paytype.pay_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setPayId(Integer payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paytype.pay_type
     *
     * @return the value of paytype.pay_type
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paytype.pay_type
     *
     * @param payType the value for paytype.pay_type
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }
}