package com.linxi.entity;

import java.io.Serializable;

public class Referral implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referral.r_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer rId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referral.r_c_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer rCId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referral.r_fail_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer rFailHId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referral.r_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer rHId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table referral
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referral.r_id
     *
     * @return the value of referral.r_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referral.r_id
     *
     * @param rId the value for referral.r_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referral.r_c_id
     *
     * @return the value of referral.r_c_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getrCId() {
        return rCId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referral.r_c_id
     *
     * @param rCId the value for referral.r_c_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setrCId(Integer rCId) {
        this.rCId = rCId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referral.r_fail_h_id
     *
     * @return the value of referral.r_fail_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getrFailHId() {
        return rFailHId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referral.r_fail_h_id
     *
     * @param rFailHId the value for referral.r_fail_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setrFailHId(Integer rFailHId) {
        this.rFailHId = rFailHId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referral.r_h_id
     *
     * @return the value of referral.r_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getrHId() {
        return rHId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referral.r_h_id
     *
     * @param rHId the value for referral.r_h_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setrHId(Integer rHId) {
        this.rHId = rHId;
    }
}