package com.linxi.entity;

import java.io.Serializable;
import java.util.Date;

public class Reroute implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reroute.re_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer reId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reroute.re_c_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer reCId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reroute.re_first_time
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Date reFirstTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reroute.re_time
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Date reTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reroute.re_cause
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private String reCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reroute
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reroute.re_id
     *
     * @return the value of reroute.re_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getReId() {
        return reId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reroute.re_id
     *
     * @param reId the value for reroute.re_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setReId(Integer reId) {
        this.reId = reId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reroute.re_c_id
     *
     * @return the value of reroute.re_c_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getReCId() {
        return reCId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reroute.re_c_id
     *
     * @param reCId the value for reroute.re_c_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setReCId(Integer reCId) {
        this.reCId = reCId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reroute.re_first_time
     *
     * @return the value of reroute.re_first_time
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Date getReFirstTime() {
        return reFirstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reroute.re_first_time
     *
     * @param reFirstTime the value for reroute.re_first_time
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setReFirstTime(Date reFirstTime) {
        this.reFirstTime = reFirstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reroute.re_time
     *
     * @return the value of reroute.re_time
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Date getReTime() {
        return reTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reroute.re_time
     *
     * @param reTime the value for reroute.re_time
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setReTime(Date reTime) {
        this.reTime = reTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reroute.re_cause
     *
     * @return the value of reroute.re_cause
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public String getReCause() {
        return reCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reroute.re_cause
     *
     * @param reCause the value for reroute.re_cause
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setReCause(String reCause) {
        this.reCause = reCause;
    }
}