package com.linxi.entity;

import java.io.Serializable;

public class Stype implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stype.st_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private Integer stId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stype.st_type
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private String stType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stype
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stype.st_id
     *
     * @return the value of stype.st_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public Integer getStId() {
        return stId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stype.st_id
     *
     * @param stId the value for stype.st_id
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setStId(Integer stId) {
        this.stId = stId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stype.st_type
     *
     * @return the value of stype.st_type
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public String getStType() {
        return stType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stype.st_type
     *
     * @param stType the value for stype.st_type
     *
     * @mbg.generated Sat Aug 22 10:46:35 CST 2020
     */
    public void setStType(String stType) {
        this.stType = stType;
    }
}