package com.linxi.entity;

import java.io.Serializable;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbg.generated Thu Aug 20 21:32:10 CST 2020
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_name
     *
     * @mbg.generated Thu Aug 20 21:32:10 CST 2020
     */
    private String uName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_password
     *
     * @mbg.generated Thu Aug 20 21:32:10 CST 2020
     */
    private String uPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_role_id
     *
     * @mbg.generated Thu Aug 20 21:32:10 CST 2020
     */
    private Integer uRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role
     *
     * @mbg.generated Thu Aug 20 21:32:10 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbg.generated Thu Aug 20 21:32:10 CST 2020
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbg.generated Thu Aug 20 21:32:10 CST 2020
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_name
     *
     * @return the value of user.u_name
     *
     * @mbg.generated Thu Aug 20 21:32:10 CST 2020
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_name
     *
     * @param uName the value for user.u_name
     *
     * @mbg.generated Thu Aug 20 21:32:10 CST 2020
     */
    public void setuName(String uName) {
        this.uName = uName;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_password
     *
     * @return the value of user.u_password
     *
     * @mbg.generated Thu Aug 20 21:32:10 CST 2020
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_password
     *
     * @param uPassword the value for user.u_password
     *
     * @mbg.generated Thu Aug 20 21:32:10 CST 2020
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_role_id
     *
     * @return the value of user.u_role_id
     *
     * @mbg.generated Thu Aug 20 21:32:10 CST 2020
     */
    public Integer getuRoleId() {
        return uRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_role_rd
     *
     * @param uRoleId the value for user.u_role_rd
     *
     * @mbg.generated Thu Aug 20 21:32:10 CST 2020
     */
    public void setuRoleId(Integer uRoleId) {
        this.uRoleId = uRoleId;
    }

    @Override
    public String toString() {
        return "User{" +
                "uId=" + uId +
                ", uName='" + uName + '\'' +
                ", uPassword='" + uPassword + '\'' +
                ", uRoleId=" + uRoleId +
                '}';
    }
}